### ISSUE TITLE
Replace strips what comes after the tag

### ISSUE THREAD

**Issue by ulodciv** [cloudflare/lol-html#207]
I might be doing something wrong, but I just can figure out what:
```
    #[test]
    fn fix_tag_replace() {
        let out_s = rewrite_str(
            "<p><iframe /></p>",
            RewriteStrSettings {
                element_content_handlers: vec![element!("iframe", |el| {
                    el.replace("<br />", ContentType::Html);
                    Ok(())
                })],
                ..RewriteStrSettings::default()
            },
        )
        .unwrap();
        assert_eq!(&out_s, "<p><br /></p>");
    }
```
gives:
```
assertion `left == right` failed
  left: "<p><br />"
 right: "<p><br /></p>"
```

**Comment by bglw** [comment]
(Not a maintainer of lol-html)

The core issue here is that iframes are not a self-closing element. The `/>` in an HTML element does nothing — so in this case it's the same as writing `<iframe>`. (Likewise `<br />` is the same as `<br>` — it always _does_ self-close).

Since it isn't a self-closing element, lol-html will be "closing" it with the next closing tag it sees. I don't know what the project's goals are about these cases, but ultimately it isn't valid HTML going in so there are fewer guarantees about what comes out.

In this case the fix is to change the input to the valid HTML: `<p><iframe></iframe></p>`.

**Comment by ulodciv** [comment]
Thanks for the explanation. I'll close this now.
